version: '3.9'
services:
  api_las_arrias_service_dev:
    build:
      context: .
      dockerfile: dockerfile.dev
    container_name: api_las_arrias_container_dev
    volumes:
      - .:/api_las_arrias_dev
      - /api/node_modules
    command: npm run dev
    ports:
      - "8080:8080"