# syntax=docker/dockerfile:1
FROM node:22.18.0-alpine

RUN adduser -D -u 1001 userdev

WORKDIR /api_las_arrias_devcontainer

# Dar permisos al nuevo usuario sobre /api_las_arrias_devcontainer
RUN chown -R userdev:userdev /api_las_arrias_devcontainer


# Copiamos solo los archivos que describen las dependencias.
COPY --chown=userdev:userdev package.json package-lock.json ./


USER userdev


RUN npm ci

COPY --chown=userdev:userdev . .