version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: dockerfile.dev
    container_name: api_las_arrias_prod
    command: npm run prod
    ports:
      - "8080:8080"
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    container_name: las_arrias_redis_prod
    ports:
      - "6379:6379"